### ISSUE TITLE
Update for current style

### ISSUE THREAD

**Issue by Rarst** [nicolashery/markdownpad-github#12]
GitHub had applied noticeable redesign of markdown rendering while back on site.

Not confident about differences / tweaks for the app required to make a pull request, but I had extracted and cleaned up [current version of markdown styling](https://gist.github.com/Rarst/5ebebddc9cfcf04eb99f) out of their CSS.

**Comment by evanwon** [comment]
Thank you for the suggestion! I haven't followed it closely, can you comment on some of the changes made to GitHub's Markdown styling?

**Comment by Rarst** [comment]
From what I noticed:
- font stack is different
- text sizes are slightly larger
- margins on things are slightly larger
- headings sizes use em not px

See the linked gist for the rest. It's not drastically different, but enough to be visually different.
