### ISSUE TITLE
Problem with bulleted lists

### ISSUE THREAD

**Issue by artfuldev** [nicolashery/markdownpad-github#3]
When a title is followed by a description, and immediately followed by a bulleted list, it is mistakenly treated as an extended description, unlike in github. Is this a problem with MarkdownPad or with the CSS?

For an example, see my
https://github.com/kenshinthebattosai/customBotConsole#ongoing-branches-of-work
section in MP

**Comment by nicolashery** [comment]
I believe in Markdown,  [block elements](http://daringfireball.net/projects/markdown/syntax#block) like paragraphs (what you call "description"), lists, etc. should be separated by one or more blank lines.

So, taking from your example, the raw text should be:

```
## Ongoing Branches of Work

(to be updated every once branches of work are finished)

* [kenshinthebattosai](http://www.github.com/kenshinthebattosai) currently working on an improved implementation of least squares scan-matching.
* [balakumar-s](http://www.github.com/balakumar-s) currently working on segmentation of laser readings for line fitting and line fitting.
* [kyaswanth93](http://www.github.com/kyaswanth93) currently working on understanding the working of the bot.
```

This will render correctly. Versus the original which was:

```
##Ongoing Branches of Work
(to be updated every once branches of work are finished)
* [kenshinthebattosai](http://www.github.com/kenshinthebattosai) currently working on an improved implementation of least squares scan-matching.
* [balakumar-s](http://www.github.com/balakumar-s) currently working on segmentation of laser readings for line fitting and line fitting.
* [kyaswanth93](http://www.github.com/kyaswanth93) currently working on understanding the working of the bot.
```

Hope this helps!
Nicolas

**Comment by artfuldev** [comment]
Thanks, I didn't know that. I was just concerned that github displays it perfectly, while MP didn't. Thanks for the clarification! :)
Nice work, by the way. I use it on a regular basis. Rocks!!!

**Comment by nicolashery** [comment]
No problem! Cheers.

/cc @evanwon

**Comment by evanwon** [comment]
@nicolahery Awesome answer, thanks :+1: :)
