### ISSUE TITLE
Margin issue in ordered/unordered lists with code

### ISSUE THREAD

**Issue by evanwon** [nicolashery/markdownpad-github#4]
When creating an ordered or unordered list, if a nested item follows a parent item with a code block, a visual gap is present.

![2013-02-10_16h33_27](https://f.cloud.github.com/assets/972799/143900/e72c4d16-73d1-11e2-941d-a0a1e2c99659.png)

Here is the raw Markdown to recreate the issue:

```
**Nested list problem:**

- Line but with `code in it`
 - Nested item, note the spacing above
- Another item in the list

**No problem here:**

- Line but with no code
 - Nested item, no spacing issue
- Another item in the list

**It affects ordered lists with code as well**

1. hello `world`
 2. this has a rendering issue
2. world
```

**Comment by evanwon** [comment]
It looks like the issue stems from Line 38, but I'd like to get your feedback on what the best way to solve the issue: https://github.com/nicolahery/markdownpad-github/blob/master/markdownpad-github.css#L38

**Comment by nicolashery** [comment]
**Nested list problem:**
- Line but with `code in it`
  - Nested item, note the spacing above
- Another item in the list

**No problem here:**
- Line but with no code
  - Nested item, no spacing issue
- Another item in the list

**It affects ordered lists with code as well**
1. hello `world`
   1. this has a rendering issue
2. world

**Comment by nicolashery** [comment]
Interesting. You see that GitHub actually didn't plan for nested `ol` :)

I would replace the statement on line 116
 https://github.com/nicolahery/markdownpad-github/blob/master/markdownpad-github.css#L116

With the following:

``` css
ul li > :first-child, 
ol li > :first-child, 
ul li ul:first-of-type, 
ol li ol:first-of-type, 
ul li ol:first-of-type, 
ol li ul:first-of-type {
  margin-top: 0px;
}
```

Let me know how that works.

Cheers

**Comment by evanwon** [comment]
Seems to fix the problem for me! Yes I see the GitHub `<ol>` issue as well. Would you like me to send a pull request?

**Comment by nicolashery** [comment]
Sweet.

Yup, I'd appreciate the pull request :)

**Comment by nicolashery** [comment]
Commenting in the future.

**Comment by evanwon** [comment]
Hm?

**Comment by nicolashery** [comment]
Sorry, I was fooling around ;)
I just found it funny that it says "in a few seconds" when you just post a comment. I wanted to take a screenshot :p

![commenting-in-the-future](https://f.cloud.github.com/assets/1306536/143927/b945f15e-73d6-11e2-9d47-77720f8022d9.png)

**Comment by evanwon** [comment]
Haha I gotcha. Nice.

**Comment by nicolashery** [comment]
Fixed with https://github.com/nicolahery/markdownpad-github/commit/d5e7ce436666e7d4a2eeb12e7f8261dacceb3565
