### ISSUE TITLE
Readme outdated after MarkdownPad 2 release

### ISSUE THREAD

**Issue by nicolashery** [nicolashery/markdownpad-github#6]
Hey @evanwon,

I'm thinking I need to update the `README.md` of this repo now that you released MarkdownPad 2...

Any ideas on what it should say?

Thanks,
Nicolas

**Comment by evanwon** [comment]
Definitely. I'll throw together some ideas ASAP and post them here. Good thinking!

**Comment by timss** [comment]
Should be noted that this stylesheet is included.

**Comment by evanwon** [comment]
Yar, 17 days ago I said I'd work on this. I'm officially terrible. :)

**Comment by timss** [comment]
No biggie, easy to figure out.
Oh and also, I must say I really like MarkdownPad 2, great job! A little annoying that I couldn't find where to disable spelling, but I "fixed" it by deleting everything in %localappdata%\MarkdownPad2\dictionaries :)

**Comment by evanwon** [comment]
Thank you so much!

Yep, deleting the dictionaries will work, but you can also disable it under `View` &rarr; `Enable Spell Check`. 

I should probably document that feature.

**Comment by timss** [comment]
Oh, there it was! I was looking under options, because that's where you could choose what dictionary to use. Other than that I think the interface is really easy to use (and good looking)!

**Comment by evanwon** [comment]
Thanks!

I added it to the FAQ: http://markdownpad.com/faq.html#disablespellcheck

And I'll work on making that a little easier to find in the future. Maybe spell check languages should just be adjustable via a menu item, rather than going into Options (or in addition to).

**Comment by timss** [comment]
Great stuff :)

**Comment by nicolashery** [comment]
Hey @evanwon I'm going to quickly push a new README.md to `master`, just with a couple lines (see below). At some point we could add a little snippet telling people if they see an inconsistency with GitHub's Markdown rendering (like GitHub changes a style) they are more than welcome to submit a pull request? :)

New `README.md` preview:

# GitHub stylesheet for MarkdownPad

**NOTE**: As of [MarkdownPad 2](http://markdownpad.com/), this stylesheet is included in the software, along with all the [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/) goodies! If you are upgrading from the first version of MarkdownPad, make sure you read [Introducing MarkdownPad 2](http://markdownpad.com/news/2013/introducing-markdownpad-2/) for a nice overview of what's new!

**Comment by evanwon** [comment]
@nicolahery Sounds awesome, thanks for putting that together. 

Maybe want to reference the [Introducing MarkdownPad 2](http://markdownpad.com/news/2013/introducing-markdownpad-2/) post for people who are upgrading from the old version somehow?

**Comment by nicolashery** [comment]
How does that look?

**Comment by evanwon** [comment]
Wonderful! :thumbsup:

**Comment by nicolashery** [comment]
Awesome. Fixed in https://github.com/nicolahery/markdownpad-github/commit/0027949e4e3269e314cdf6cfe5bc217fc5d1e649

This repo seems to be like number 5 in Google when you search for "github markdown stylesheet" so that might explain how people are finding this. Hopefully now they'll naturally flow to (and buy! :p) the great MarkdownPad 2!

Cheers
