### ISSUE TITLE
Update to latest GitHub CSS

### ISSUE THREAD

**Issue by oliversalzburg** [nicolashery/markdownpad-github#8]
I noticed that a few things changed in the Markdown rendering on GitHub.

For example, they have a certain style now for `<kbd>` (simulating the look of a keyboard key). Also, they have a new style for `<hr>`.

I noticed this in the `README` rendering of a project I'm working on: https://github.com/oliversalzburg/TimeBeam

**Comment by evanwon** [comment]
@oliversalzburg For the `<hr>`, MarkdownPad's CSS is deliberately different because GitHub's CSS is using an image file.

**Comment by evanwon** [comment]
Here's the tag for keyboard keys: `<kbd>Ctrl</kbd>` which renders to: <kbd>Ctrl</kbd>

**Comment by evanwon** [comment]
How do we feel about #9?

**Comment by oliversalzburg** [comment]
Seems like this is the original CSS for it:

```
kbd{
    background-color:#dddddd;
    background-image:-moz-linear-gradient(#f1f1f1, #ddd);
    background-image:-webkit-linear-gradient(#f1f1f1, #ddd);
    background-image:linear-gradient(#f1f1f1, #ddd);
    background-repeat:repeat-x;
    border-radius:2px;
    border:1px solid #ddd;
    border-bottom-color:#ccc;
    border-right-color:#ccc;
    padding:1px 4px;
    line-height:10px;
    font-family:"Helvetica Neue", Helvetica, Arial, sans-serif
}
```

Preceded by:

```
code,kbd,pre,samp{
    font-family:monospace, serif;
    font-size:1em
}
```

But, as you already noted, it doesn't render a gradient background in MDP.

**Comment by evanwon** [comment]
@oliversalzburg The last section of code uses a monospace font, which doesn't seem to match up with what GitHub is using in production: <kbd>Ctrl</kbd>

**Comment by oliversalzburg** [comment]
@evanwon Right, the `font-family` is overridden by the `kbd` style. But the `font-size` should be inherited, if it is at all important.

**Comment by nicolashery** [comment]
Merged in https://github.com/nicolashery/markdownpad-github/commit/eaa2da45a060034d70efabf4e9ac2d1957c348dd

Thanks!

**Comment by evanwon** [comment]
:thumbsup:
